;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Attack.Middle",DevComment="")
+GameplayTagList=(Tag="Ability.Attack.Normal",DevComment="")
+GameplayTagList=(Tag="Ability.Attack.Strong",DevComment="")
+GameplayTagList=(Tag="DodgeTag",DevComment="")
+GameplayTagList=(Tag="Enemy.Attack01",DevComment="")
+GameplayTagList=(Tag="Iai.Sheathing",DevComment="")
+GameplayTagList=(Tag="Invincible",DevComment="")
+GameplayTagList=(Tag="IsDodge",DevComment="")
+GameplayTagList=(Tag="IsEvent",DevComment="")
+GameplayTagList=(Tag="LoopCounter",DevComment="")
+GameplayTagList=(Tag="",DevComment="")
+GameplayTagList=(Tag="PlayerNotify.CantAttack",DevComment="")
+GameplayTagList=(Tag="PlayerNotify.NextTag0",DevComment="")
+GameplayTagList=(Tag="PlayerNotify.NextTag1",DevComment="")
+GameplayTagList=(Tag="PlayerNotify.NextTag2",DevComment="")
+GameplayTagList=(Tag="PlayerNotify.NextTag3",DevComment="")
+GameplayTagList=(Tag="PlayerNotify.NextTag4",DevComment="")
+GameplayTagList=(Tag="Skill.Kaguya",DevComment="")
+GameplayTagList=(Tag="SlowMontage",DevComment="")
+GameplayTagList=(Tag="State.Attacking.Skill",DevComment="")
+GameplayTagList=(Tag="State.Skill.Kaguya",DevComment="")
+GameplayTagList=(Tag="State.Skill.Kintaro",DevComment="")

